version: "3"
services:
    database:
        image: mysql:8.0
        container_name: database
        restart: always
        hostname: mysql01
        ports:
            - "33062:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=opscom_dev
            - MYSQL_USER=opscom_user
            - MYSQL_PASSWORD=123
        volumes:
            - ./backend/db/dbdata:/var/lib/mysql
            - ./backend/db/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            dockerfile: docker/Dockerfile
        container_name: backend
        tty: true
        ports:
            - "8001:80"
        working_dir: /var/www/html
        volumes:
            - ./backend/src/:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=database
            - DB_DATABASE=opscom_dev
            - DB_USERNAME=root
            - DB_PASSWORD=123
            - DB_PORT=3306
        networks:
            - app-network

    # frontend:
    #     build:
    #         context: ./frontend
    #         dockerfile: docker/Dockerfile
    #     container_name: frontend
    #     ports:
    #         - "8001:3000"
    #     volumes:
    #         - ./frontend:/app
    #         - /app/node_modules
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #     networks:
    #         - app-network


#Docker Networks
networks:
    app-network:
            driver: bridge